### ISSUE TITLE
error when add --exts

### ISSUE THREAD

**Issue by iwasnobody** [yaricom/dogs-vs-cats#1]
the script report error after adding "--exts ['.jpeg', '.jpg', '.png']", not know the reason
[root@ip-10-0-0-163 tools]# python im2rec.py --list True --exts ['.jpeg', '.jpg', '.png'] --recursive True --train-ratio 0.95 /disk/data_set_train/imgdata /disk/data
usage: im2rec.py [-h] [--list LIST] [--exts EXTS] [--chunks CHUNKS]
                 [--train-ratio TRAIN_RATIO] [--test-ratio TEST_RATIO]
                 [--recursive RECURSIVE] [--shuffle SHUFFLE]
                 [--pass-through PASS_THROUGH] [--resize RESIZE]
                 [--center-crop CENTER_CROP] [--quality QUALITY]
                 [--num-thread NUM_THREAD] [--color {-1,0,1}]
                 [--encoding {.jpg,.png}] [--pack-label PACK_LABEL]
                 prefix root
im2rec.py: error: unrecognized arguments: /disk/data_set_train/imgdata /disk/data

**Comment by iwasnobody** [comment]
remove the space in ['.jpeg', '.jpg', '.png'] to ['.jpeg','.jpg','.png'], no error report but there is nothing in the created file imgdata_val.lst and imgdata_train.lst

**Comment by yaricom** [comment]
Hello, thanks for reporting.

With current realization you can not mix JPEG and PNG files. Only one type of files should be used. By default it’s assumed as JPEG. If you need to use PNG then provide corresponding values for the following command line arguments 

- exts 

- encoding

Hope this will help.

**Comment by iwasnobody** [comment]
Got it! Thanks
